### ISSUE TITLE
SOS - published website

### ISSUE THREAD

**Issue by trebird** [trebird/responsive-recipe-book#1]
Hi @thomasjbradley

I've been wanting to ask you about this because I had the same issue with my Animal Rescue website. When I follow the published URL from GitHub, the website displays VERY differently than from my files and does not pick up any style.

Apologies if I've missed something really obvious, but at a loss.

Thank you!

Treawna

**Comment by thomasjbradley** [comment]
Your CSS folder has capital letters, see here:
https://github.com/trebird/responsive-recipe-book

1. Rename the folder something completely different, like `dogs-n-cats`
2. Commit all the changes
3. Rename it back to `css`—with lowercase

**Comment by trebird** [comment]
SHAMEFUL!

My sincerest apologies and one hundred thanks.
